project:
  type: website
  output-dir: docs

website:
  description: "A blog built with Quarto"
  site-url: https://mlmecham.github.io/blogs_quarto/
  title: "Personal Cite"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/MLMecham
      - icon: bluesky
        href: https://bsky.app/
      - icon: linkedin
        href: https://www.linkedin.com/in/mitchell-mecham/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



